from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Protocol, Sequence

from src.market_observation_batch_v0 import (
    MarketLifecycleWriteV0,
    MarketTradeWriteV0,
    record_market_observations_batch_v0,
)
from src.market_observation_store import (
    record_market_lifecycle,
    record_market_trade,
)
from src.market_opportunity_episode_batch_v0 import (
    MarketContinuationTriggerWriteV0,
    record_market_continuation_triggers_batch_v0,
)
from src.market_opportunity_episode_store import (
    MarketOpportunityEpisode,
    get_market_opportunity_episode,
)
from src.market_opportunity_radar import (
    MarketLifecycleObservation,
    MarketTradeObservation,
)
from src.signal_plane_episode_admission_v0 import (
    SignalPlaneEpisodeAdmissionResult,
    admit_signal_plane_trigger_snapshot,
)
from src.signal_plane_episode_bridge_v0 import (
    build_signal_plane_episode_assignment,
    market_movement_trigger_from_snapshot,
)


SIGNAL_PLANE_RESEARCH_PERSISTENCE_VERSION = "signal_plane_research_persistence_v0"


class SignalPlaneResearchRecord(Protocol):
    sequence: int
    kind: str
    event_key: str
    source_provider: str
    trade: MarketTradeObservation | None
    lifecycle: MarketLifecycleObservation | None


SignalPlaneResearchBatchItem = tuple[
    SignalPlaneResearchRecord,
    dict | None,
]


@dataclass(frozen=True)
class SignalPlaneResearchPersistResult:
    sequence: int
    observation_inserted: bool
    episode: SignalPlaneEpisodeAdmissionResult | None


@dataclass(frozen=True)
class SignalPlaneResearchBatchPersistResult:
    completed: int
    observations_inserted: int
    observation_replays: int
    trades_completed: int
    lifecycles_completed: int
    trigger_episodes: int
    new_admissions: int
    admission_replays: int
    continuation_triggers: int
    continuation_trigger_transactions: int
    sqlite_transactions: int
    max_transaction_records: int


def persist_signal_plane_research_record(
    *,
    acquisition_run_key: str,
    record: SignalPlaneResearchRecord,
    trigger_snapshot: dict | None,
    admit_episode_fn: Callable[..., bool] | None = None,
) -> SignalPlaneResearchPersistResult:
    """Persist one canonical Signal Plane record before durable episode admission.

    The caller must submit records in original Signal Plane sequence order. This
    function first makes the current causal observation durable and only then
    persists/admit any trigger generated by that same observation.
    """

    if record.kind == "trade":
        if record.trade is None:
            raise ValueError("trade TraceRecord is missing trade observation")
        inserted = record_market_trade(
            acquisition_run_key=acquisition_run_key,
            event_key=record.event_key,
            source_provider=record.source_provider,
            observation=record.trade,
        )
        episode = admit_signal_plane_trigger_snapshot(
            acquisition_run_key=acquisition_run_key,
            trigger_snapshot=trigger_snapshot,
            observation=record.trade,
            admit_episode_fn=admit_episode_fn,
        )
        return SignalPlaneResearchPersistResult(
            sequence=record.sequence,
            observation_inserted=inserted,
            episode=episode,
        )

    if record.kind == "lifecycle":
        if record.lifecycle is None:
            raise ValueError("lifecycle TraceRecord is missing lifecycle observation")
        if trigger_snapshot is not None:
            raise ValueError("lifecycle record cannot carry a market trigger")
        inserted = record_market_lifecycle(
            acquisition_run_key=acquisition_run_key,
            event_key=record.event_key,
            source_provider=record.source_provider,
            observation=record.lifecycle,
        )
        return SignalPlaneResearchPersistResult(
            sequence=record.sequence,
            observation_inserted=inserted,
            episode=None,
        )

    raise ValueError(f"unsupported TraceRecord kind: {record.kind!r}")


def _observation_write(
    *,
    acquisition_run_key: str,
    record: SignalPlaneResearchRecord,
):
    if record.kind == "trade":
        if record.trade is None:
            raise ValueError("trade TraceRecord is missing trade observation")
        return MarketTradeWriteV0(
            acquisition_run_key=acquisition_run_key,
            event_key=record.event_key,
            source_provider=record.source_provider,
            observation=record.trade,
        )
    if record.kind == "lifecycle":
        if record.lifecycle is None:
            raise ValueError("lifecycle TraceRecord is missing lifecycle observation")
        return MarketLifecycleWriteV0(
            acquisition_run_key=acquisition_run_key,
            event_key=record.event_key,
            source_provider=record.source_provider,
            observation=record.lifecycle,
        )
    raise ValueError(f"unsupported TraceRecord kind: {record.kind!r}")


def _remember_episode(
    cache: dict[str, list[MarketOpportunityEpisode]],
    episode: MarketOpportunityEpisode,
) -> None:
    bucket = cache.setdefault(episode.token_mint, [])
    for index, existing in enumerate(bucket):
        if existing.episode_key == episode.episode_key:
            bucket[index] = episode
            break
    else:
        bucket.append(episode)
    bucket.sort(
        key=lambda item: (
            item.first_trigger_observed_at,
            item.episode_key,
        )
    )


def _cached_continuation_episode(
    cache: dict[str, list[MarketOpportunityEpisode]],
    *,
    token_mint: str,
    trigger_key: str,
    observed_at: int,
) -> MarketOpportunityEpisode | None:
    for episode in reversed(cache.get(token_mint, [])):
        if (
            episode.first_trigger_key != trigger_key
            and episode.first_trigger_observed_at
            <= observed_at
            < episode.episode_closes_at
        ):
            return episode
    return None


def persist_signal_plane_research_batch(
    *,
    acquisition_run_key: str,
    items: Sequence[SignalPlaneResearchBatchItem],
    admit_episode_fn: Callable[..., bool] | None = None,
    episode_cache: dict[str, list[MarketOpportunityEpisode]] | None = None,
) -> SignalPlaneResearchBatchPersistResult:
    """Persist ordered Research Plane records with trigger-safe batching.

    Observation writes are batched. Once an episode has been synchronously
    established, continuation triggers inside that canonical episode window use
    the frozen continuation-trigger batch writer and never re-enter episode T0
    assignment/admission.

    A trigger that can create/move/select a canonical episode remains strictly
    synchronous:

        observations through N durable
        -> canonical episode assignment for N
        -> episode admission for N
        -> sequence > N

    Late-earlier triggers, first-trigger replays and triggers outside cached
    episode windows deliberately fall back to the synchronous path, preserving
    the frozen no-retroactive-enrollment semantics.
    """

    if not items:
        return SignalPlaneResearchBatchPersistResult(
            completed=0,
            observations_inserted=0,
            observation_replays=0,
            trades_completed=0,
            lifecycles_completed=0,
            trigger_episodes=0,
            new_admissions=0,
            admission_replays=0,
            continuation_triggers=0,
            continuation_trigger_transactions=0,
            sqlite_transactions=0,
            max_transaction_records=0,
        )

    expected_sequence = int(items[0][0].sequence)
    for record, trigger_snapshot in items:
        if int(record.sequence) != expected_sequence:
            raise RuntimeError(
                "research persistence batch sequence mismatch: "
                f"expected={expected_sequence} actual={record.sequence}"
            )
        if record.kind == "lifecycle" and trigger_snapshot is not None:
            raise ValueError("lifecycle record cannot carry a market trigger")
        expected_sequence += 1

    cache = episode_cache if episode_cache is not None else {}

    observations_inserted = 0
    observation_replays = 0
    trades_completed = 0
    lifecycles_completed = 0
    trigger_episodes = 0
    new_admissions = 0
    admission_replays = 0
    continuation_triggers = 0
    continuation_trigger_transactions = 0
    sqlite_transactions = 0
    max_transaction_records = 0

    pending_writes = []
    pending_continuations: list[MarketContinuationTriggerWriteV0] = []

    def flush_pending() -> None:
        nonlocal observations_inserted
        nonlocal observation_replays
        nonlocal continuation_trigger_transactions
        nonlocal sqlite_transactions
        nonlocal max_transaction_records

        if pending_writes:
            transaction_records = len(pending_writes)
            result = record_market_observations_batch_v0(tuple(pending_writes))
            observations_inserted += int(result.inserted)
            observation_replays += int(result.replayed)
            sqlite_transactions += 1
            max_transaction_records = max(
                max_transaction_records,
                transaction_records,
            )
            pending_writes.clear()

        # Continuations cannot create/move T0. Persist them only after every
        # corresponding observation in this flush is durable.
        if pending_continuations:
            record_market_continuation_triggers_batch_v0(
                tuple(pending_continuations)
            )
            continuation_trigger_transactions += 1
            pending_continuations.clear()

    for record, trigger_snapshot in items:
        pending_writes.append(
            _observation_write(
                acquisition_run_key=acquisition_run_key,
                record=record,
            )
        )
        if record.kind == "trade":
            trades_completed += 1
        else:
            lifecycles_completed += 1

        if trigger_snapshot is None:
            continue
        if record.trade is None:
            raise ValueError("triggered trade TraceRecord is missing trade observation")

        trigger_episodes += 1
        cached = None
        assignment = None
        # Snapshot reconstruction is needed only when this token already has a
        # canonical episode candidate. First/new-token triggers stay on the
        # original synchronous path without duplicate parsing.
        if cache.get(record.trade.token_mint):
            trigger = market_movement_trigger_from_snapshot(trigger_snapshot)
            assignment = build_signal_plane_episode_assignment(
                trigger=trigger,
                observation=record.trade,
            )
            cached = _cached_continuation_episode(
                cache,
                token_mint=assignment.token_mint,
                trigger_key=assignment.trigger_key,
                observed_at=assignment.observed_at,
            )
        if cached is not None and assignment is not None:
            pending_continuations.append(
                MarketContinuationTriggerWriteV0(
                    acquisition_run_key=acquisition_run_key,
                    episode_key=cached.episode_key,
                    trigger_key=assignment.trigger_key,
                    token_mint=assignment.token_mint,
                    trigger_kind=assignment.trigger_kind,
                    direction=assignment.direction,
                    chain_time=assignment.chain_time,
                    observed_at=assignment.observed_at,
                    method_version=assignment.method_version,
                    venue=assignment.venue,
                )
            )
            continuation_triggers += 1
            # Semantically this trigger belongs to an already-admitted episode.
            # Do not call the durable admission store again.
            admission_replays += 1
            continue

        # Unknown/out-of-window/late-earlier/first-trigger-replay cases retain
        # the original synchronous fail-closed path.
        flush_pending()
        episode_result = admit_signal_plane_trigger_snapshot(
            acquisition_run_key=acquisition_run_key,
            trigger_snapshot=trigger_snapshot,
            observation=record.trade,
            admit_episode_fn=admit_episode_fn,
        )
        if episode_result is None:
            raise RuntimeError("trigger snapshot produced no episode admission result")
        if episode_result.admitted:
            new_admissions += 1
        else:
            admission_replays += 1

        episode = get_market_opportunity_episode(episode_result.episode_key)
        if episode is None:
            raise RuntimeError(
                "admitted Signal Plane episode is missing from durable store"
            )
        _remember_episode(cache, episode)

    flush_pending()

    return SignalPlaneResearchBatchPersistResult(
        completed=len(items),
        observations_inserted=observations_inserted,
        observation_replays=observation_replays,
        trades_completed=trades_completed,
        lifecycles_completed=lifecycles_completed,
        trigger_episodes=trigger_episodes,
        new_admissions=new_admissions,
        admission_replays=admission_replays,
        continuation_triggers=continuation_triggers,
        continuation_trigger_transactions=continuation_trigger_transactions,
        sqlite_transactions=sqlite_transactions,
        max_transaction_records=max_transaction_records,
    )
