from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Protocol

from src.market_observation_store import (
    record_market_lifecycle,
    record_market_trade,
)
from src.market_opportunity_radar import (
    MarketLifecycleObservation,
    MarketTradeObservation,
)
from src.signal_plane_episode_admission_v0 import (
    SignalPlaneEpisodeAdmissionResult,
    admit_signal_plane_trigger_snapshot,
)


SIGNAL_PLANE_RESEARCH_PERSISTENCE_VERSION = "signal_plane_research_persistence_v0"


class SignalPlaneResearchRecord(Protocol):
    sequence: int
    kind: str
    event_key: str
    source_provider: str
    trade: MarketTradeObservation | None
    lifecycle: MarketLifecycleObservation | None


@dataclass(frozen=True)
class SignalPlaneResearchPersistResult:
    sequence: int
    observation_inserted: bool
    episode: SignalPlaneEpisodeAdmissionResult | None


def persist_signal_plane_research_record(
    *,
    acquisition_run_key: str,
    record: SignalPlaneResearchRecord,
    trigger_snapshot: dict | None,
    admit_episode_fn: Callable[..., bool] | None = None,
) -> SignalPlaneResearchPersistResult:
    """Persist one canonical Signal Plane record before durable episode admission.

    The caller must submit records in original Signal Plane sequence order. This
    function first makes the current causal observation durable and only then
    persists/admit any trigger generated by that same observation.
    """

    if record.kind == "trade":
        if record.trade is None:
            raise ValueError("trade TraceRecord is missing trade observation")
        inserted = record_market_trade(
            acquisition_run_key=acquisition_run_key,
            event_key=record.event_key,
            source_provider=record.source_provider,
            observation=record.trade,
        )
        episode = admit_signal_plane_trigger_snapshot(
            acquisition_run_key=acquisition_run_key,
            trigger_snapshot=trigger_snapshot,
            observation=record.trade,
            admit_episode_fn=admit_episode_fn,
        )
        return SignalPlaneResearchPersistResult(
            sequence=record.sequence,
            observation_inserted=inserted,
            episode=episode,
        )

    if record.kind == "lifecycle":
        if record.lifecycle is None:
            raise ValueError("lifecycle TraceRecord is missing lifecycle observation")
        if trigger_snapshot is not None:
            raise ValueError("lifecycle record cannot carry a market trigger")
        inserted = record_market_lifecycle(
            acquisition_run_key=acquisition_run_key,
            event_key=record.event_key,
            source_provider=record.source_provider,
            observation=record.lifecycle,
        )
        return SignalPlaneResearchPersistResult(
            sequence=record.sequence,
            observation_inserted=inserted,
            episode=None,
        )

    raise ValueError(f"unsupported TraceRecord kind: {record.kind!r}")
